name = "dns-monitor-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Configurar a URL do frontend para CORS
[vars]
FRONTEND_URL = "https://1886d93a.dns-monitor-frontend.pages.dev"
ADMIN_SECRET = "Sudo@0412"

[[d1_databases]]
binding = "DB"
database_name = "dns-monitor"
database_id = "b08a35ce-335b-49b7-9c98-e8a39bf18b4e"
